
abstract=
ontologyTitle=NORMA: Normative Ontology for Regulatory Machine-readable Annotations
ontologyPrefix=norma
ontologyNamespaceURI=https://w3id.org/norma-ontology#
ontologyName=NORMA ontology
thisVersionURI=https://w3id.org/norma-ontology/1.0
latestVersionURI=
previousVersionURI=
dateCreated=2026-04-15
dateModified=2026-04-25
ontologyRevisionNumber=1.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs=Leyva-Sánchez, S. et al. (2026). NORMA: Normative Ontology for Regulatory Machine-readable Annotations (Version 1.0) [Ontology]. https://w3id.org/norma-ontology/1.0
DOI=10.5281/zenodo.19765302
status=Published
logo=https://w3id.org/norma-ontology/assets/logo.png
description=Publication-quality ontology aligned to the NORMA annotation model and BPMN legal compliance workflow.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=ontology#;core;prov-o#;&lt;http://xmlns.com/foaf/0.1/&gt;
importedOntologyURIs=http://data.europa.eu/eli/ontology#;http://www.w3.org/2004/02/skos/core;http://www.w3.org/ns/prov-o#;http://xmlns.com/foaf/0.1/
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=https://github.com/norma-project/norma-ontology
seeAlso=https://www.w3.org/TR/swbp-n-aryRelations/
fundingGrants=
funders=
