
abstract=
ontologyTitle=NORMA-O: The NORMA Ontology for Legal Norm Annotations
ontologyPrefix=norma
ontologyNamespaceURI=https://w3id.org/def/norma-o#
ontologyName=NORMA ontology
thisVersionURI=https://w3id.org/def/norma-o/1.0
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=2026-04-28
ontologyRevisionNumber=1.0
licenseURI=http://purl.org/NET/rdflicense/cc-by-nc4.0
licenseName=Creative Commons CC-BY-NC
licenseIconURL=null
citeAs=Leyva-Sánchez, S. et al. (2026). NORMA-O: The NORMA Ontology for Legal Norm Annotations (Version 1.0) [Ontology]. https://w3id.org/def/norma-o/1.0
DOI=10.5281/zenodo.19765302
status=Published
logo=https://w3id.org/def/norma-o/assets/norma-o.png
description=Formal ontology for representing machine-readable legal norm annotations, their legal context, conditional applicability, provenance, source traceability, lifecycle status, and controlled classification values in the NORMA toolkit.
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=;
contributorsURI=;
contributorsInstitution=;
contributorsInstitutionURI=;
importedOntologyNames=ontology#;core;prov-o#;&lt;http://xmlns.com/foaf/0.1/&gt;
importedOntologyURIs=http://data.europa.eu/eli/ontology#;http://www.w3.org/2004/02/skos/core;http://www.w3.org/ns/prov-o#;http://xmlns.com/foaf/0.1/
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=https://github.com/sheyls/norma-semantic-toolkit
seeAlso=http://www.estrellaproject.org/lkif-core/norm.owl;https://www.w3.org/TR/swbp-n-aryRelations/
fundingGrants=
funders=
